AWSTemplateFormatVersion: "2010-09-09"
Description: "add EIP"

Resources:
  # EC2インスタンス（WEB)
  EC2Instance03:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: subnet-010a40742adf5bc86
      InstanceType: t2.micro
      AvailabilityZone: ap-northeast-1a
      KeyName: ec2-test2
      Monitoring: false
      ImageId: ami-068a6cefc24c301d2
      InstanceInitiatedShutdownBehavior: stop
      SecurityGroupIds:
        - sg-0429ac2f744783f9e
      Tags:
        - Key: Name
          Value: SV#3

# ElasticIP:
#     Type: "AWS::EC2::EIP"
#     Properties:
#       InstanceId: !Ref EC2Instance03
#       Domain: vpc

# ElasticIp定義  
  ElasticIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: "13.230.185.29"
      InstanceId: !Ref EC2Instance03
#    DependsOn: EC2Instance03
